### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by jorbor** [prirodancoder/valant-test#1]
Readme states to do `./mvnw deploy` to start the app. However, it seems like this tries to copy files to a repository? In any case, I get an error

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project myjpa: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]`

I can add this to pom.xml, but don't know what a good value would be.

**Comment by jorbor** [comment]
I see, this copies a jar to target dir, and I can run that.

**Comment by mingrutar** [comment]
I added gradle. Try 
./gradlew build
./gradlew bootRun

It works on mine. It has a wrapper and supposedly does not require gradle be install. Let me know how it goes. I am learning gradle.....
