### ISSUE TITLE
Bug: duplicate labels

### ISSUE THREAD

**Issue by jorbor** [prirodancoder/valant-test#3]
Duplicate labels can be inserted, and once this occurs, they can't be removed.

```
curl -H "Content-Type: application/json" -X POST -d '{"label":"foo","expiration":1459468188, "type":"A"}' http://localhost:8080/
curl -H "Content-Type: application/json" -X POST -d '{"label":"foo","expiration":1459468188, "type":"A"}' http://localhost:8080/
```

```
$ curl -i -H "Accept: application/json" -X DELETE http://localhost:8080/foo
HTTP/1.1 500 Internal Server Error
Server: Apache-Coyote/1.1
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 31 Mar 2016 23:50:32 GMT
Connection: close

{"timestamp":1459468232671,"status":500,"error":"Internal Server Error","exception":"org.springframework.dao.IncorrectResultSizeDataAccessException","message":"result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements","path":"/foo"}

```

**Comment by mingrutar** [comment]
Thank you for reviewing. Glad that you have launching work - always the most trouble step and thank you for the effort. 
It allows duplicates. I was wondering whether I should check the dups. The requirements does not specify. The dup check is easy. The question is if the item exist, what do we return?

**Comment by mingrutar** [comment]
Change the behavior to: 
case 1) New item:  add the item and return HTTP status CREATED. 
case 1) Existing item:  ignore the item and return HTTP status UNPROCESSABLE_ENTITY. 

Added unit test MyjpaApplicationTests::createDuplicatedItem()

More details is in readme.txt, at the top. but file is a bit messy, sorry for that.
