### ISSUE TITLE
Expiration doesn't seem to work?

### ISSUE THREAD

**Issue by jorbor** [prirodancoder/valant-test#4]
`curl -H "Content-Type: application/json" -X POST -d '{"label":"foo","expiration":1459468232671, "type":"A"}' http://localhost:8080/`

Never see an expiration notice. Am I doing something wrong?

**Comment by mingrutar** [comment]
I asked the question about expected notification mechanism. The recruiter said that he passes the question over but I've not received the answer yet. I proceeded with a simple solution - the system log an entry about the notification. 
What king notification mechanism do you expect?

**Comment by mingrutar** [comment]
the notification is built on Spring EventBus. Currently, the receiver (see SimpleReceiver.java) writes a message to the log. 
For quick verification: use branch  'fixIssues'. It seeds db with 2 expired items, and you will find the message logged by notification receiver. See readMe.txt for more details.
The reason you did not see the notification is that the expiration is based on day, that is how I understand the requirement. 
Please let me know if you have suggestion and/or any questions.

**Comment by mingrutar** [comment]
Unit tests for  expired and removed notifications works.
